### ISSUE TITLE
wxPython's GetHandle() returns 0 with wxPython 3.0/4.0 on Linux

### ISSUE THREAD

**Issue by cztomczak** [cztomczak/cefpython#349]
On Linux with wxPython 3.x / 4.x window handle is not yet available even though Show() was called and it causes in the wxpython.py example to open two windows, one blank window and another window with CEF browser. This effect is because window handle passed to CEF is 0, thus CEF creates a top-level window on its own.

The solution is to delay embedding browser by a bit and window handle becomes available then. Time of 1ms is not enough, 10ms seems fine, but to be sure I've used 20ms. Example works fine with such code:

```
        # On Linux must show before embedding browser, so that handle
        # is available (Issue #347).
        if LINUX:
            self.Show()
            # In wxPython 3.0 and wxPython 4.0 handle is still
            # not yet available, must delay embedding browser
            # (Issue #349).
            if wx.version().startswith("3.") or wx.version().startswith("4."):
                wx.CallLater(20, self.embed_browser)
            else:
                # This works fine in wxPython 2.8
                self.embed_browser()
        else:
            self.embed_browser()
            self.Show()
```

Issue originally reported on the Forum:
https://groups.google.com/d/topic/cefpython/ZBXEdOR3svw/discussion

**Comment by cztomczak** [comment]
Fixed in b359129.

**Comment by cztomczak** [comment]
I just ran an application running wxPython 4 and delaying embedding by 20ms was not enough. It didn't throw error, but it seems that GetHandle returned '0', because I was seeing that browser was embedded in a separate window created implicitilly by CEF, thus I was seeing in total two windows. Increasing the delay to 40ms fixes it, however this may still be not enough. TODO:

1. Increase the delay to embed browser to 100ms
2. Check that GetHandle doesn't return '0' with some assert

**Comment by cztomczak** [comment]
Additional fixes in commit 9c567bf.

**Comment by mitras2** [comment]
I'm currently having the same problem on 
wxPython 4.0.4 
CEFPython 66.0 
Python 3.7
GNOME 3.32.1
(Manjaro) Linux

Starting the wxPython example crashes the app after a very short time with `Window handle not available`.
Setting the delay in `wx.CallLater(100, self.embed_browser)` to a longer time (tested up to 8 seconds) does not solve the problem. The call to `GetHandle()` alwas returns an integer 0 for the wx.Panel and for the wx.Frame.
When I did umcomment the `assert self.browser_panel.GetHandle(), "Window handle not available"` two windows were created: One wxPython-Window and one CEFPython Window.

I wonder wether this is a bug in wxPython on Linux (with GTK3)

**Comment by cztomczak** [comment]
@mitras2 Some GTK 3 version won't work with CEF/Chromium. See https://github.com/cztomczak/cefpython/issues/393#issuecomment-390989144 . See also last comment by rocker71 there.

**Comment by mitras2** [comment]
I had also posted the problem at the [wxWidgets/Phoenix Issue tracker](https://github.com/wxWidgets/Phoenix/issues/1217).
The problem is that I am on a system using wayland and GetHandle() does not yet work for wayland, so it always returns 0 [mentioned here](https://github.com/wxWidgets/Phoenix/issues/1217#issuecomment-488541037).

This leads to a second question:
Does CEFPython support Wayland-Handle-Equivalents to append it's content to the Panel/Frame?

BTW:
Thanks for all the work you already put into this project! CEFPython is a awesome Framework and I really enjoy working with it :-)

**Comment by cztomczak** [comment]
Upstream CEF master started supporting ozone builds which can run with different platform backends (Wayland, X11, etc). However currently this is supported only with the Views framework (CEF window management framework). Details in Issue #523.

**Comment by RobinD42** [comment]
Instead of fiddling with timer delays you may want to try using `EVT_WINDOW_CREATE`. On X11 based environments, at least, the event will be sent after the window has been fully created on the X server.
